#!/bin/bash

# add user 
adduser --system --home /tmp --shell /bin/sh --disabled-password --gecos 'Bridge User,,,' nuage

# link runlevel scripts
# install config
[ -f /etc/nuage/nuage.cfg ] || install -m 0644 /etc/nuage/nuage.cfg.dist /etc/nuage/nuage.cfg

# check for serial override
if [ -x /etc/nuage/serial.cfg ] ; then
	. /etc/nuage/serial.cfg
elif grep sun7i /proc/cpuinfo
	SERIALDEV=ttyS2
else
	SERIALDEV=ttyAMA0
fi

# install daemon
update-rc.d -f nuage defaults
/etc/init.d/nuage start

# add line to /etc/inittab
grep $SERIALDEV /etc/inittab | grep -v '^#' | while read line ; do
    sed -i "\%${line}%d" /etc/inittab  
done
echo 'T0:23:respawn:/sbin/getty -L -a nuage '${SERIALDEV}' 19200' >> /etc/inittab 
# change the boot parameter for serial line to avoid confusion
# this will just have an effect on RPi
sed -i 's/console='${SERIALDEV}',115200/console='${SERIALDEV}',19200/g' /boot/cmdline.txt 
init Q
exit 0
